### PR TITLE
 tracking of payment on etherscan #515

### LINKED ISSUE #515: As Exchange Union I want to track the payment of funded issues
### Precondition

- A project has succesfully funded an issue
- A developer has succesfully solved an issue
- A developer claims an issue

### Scope
- FundRequestNotifier posts a message  that an issue is succesfully claimed
- A funder or developer can click on a link to track the payment on a blockexplorer (for example : etherscan)

### Postcondition
-  The funds can succesfully be tracked on a block explorer

### Acceptance Criteria
- Visible on GitHub Issue

"Thank you <solver> for your code contribution. The reward linked to this issue has been transferred to your account. **Please track payment details <here>.** 

Looking for more? Feel free to browse through all funded requests."

### Attachements
screen shot 2018-07-31 at 12 40 42

### Additional Question
-  Does the block explorer text + link only need to be added when an issue is claimed or also when it is funded
screen shot 2018-07-31 at 12 40 50

### PR DESCRIPTION
**Pull request by marc0olo**
Fixes #515 
in order to run on windows the single question marks in the typechain command were removed additionally

### CODE REVIEW

**Comment by marc0olo** [comment]
ohh yes I missed that one

**Comment by marc0olo** [comment]
@nico-ptrs still doesn't seem to work. is it possible to access jenkins-log from public?

**Comment by nico-ptrs** [comment]
@marc0olo it's a different test that is failing now.
I've enabled anonymous read access on the build server, so you should be able to access [your build](https://ci.fundrequest.io/job/FundRequest/job/FundRequest%20CI/job/platform/view/change-requests/job/PR-524/).

**Comment by nico-ptrs** [comment]
I just approved the pull request.
We will give it a test on our testing environment first and if that's successful, the branch will be merged into develop and you will be able to claim your reward.
Thanks again for your patience and effort!

**Comment by karelstriegel** [comment]
Perfect, very good job 👍 👍

**Pull request merged**
